#!/bin/bash
# Setup helper script for the Weather Forecast Webapp

echo "=================================="
echo "Weather Forecast Webapp - Setup"
echo "=================================="
echo ""
echo "Before running the webapp, you need to:"
echo ""
echo "1. Create an app registration in Azure Portal named:"
echo "   'Weather App Webapp - <Your Initials>'"
echo ""
echo "2. Configure these values in app_config.py:"
echo "   - TENANT_ID: Find on your app registration Overview page"
echo "   - CLIENT_ID: Find on your app registration Overview page"
echo "   - API_APP_ID_URI: Find in your Weather API app registration"
echo "                     under 'Expose an API' (format: api://guid)"
echo ""
echo "3. In your app registration, set the redirect URI to:"
echo "   http://localhost:5000/getAToken"
echo ""
echo "4. Add delegated API permissions for 'access_as_user' scope"
echo ""
echo "5. Create a client secret and note the value"
echo ""
echo "6. Ensure admin consent is granted"
echo ""
echo "Then run:"
echo "  pip install -r requirements.txt"
echo "  python app.py"
echo ""
echo "=================================="
